# Generated by Django 4.0.4 on 2022-05-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homeModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('course_img1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('course_img2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('course_img3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('course_img4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('popular_course_img1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('popular_course_img2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('popular_course_img3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('popular_course_price1', models.IntegerField()),
                ('popular_course_price2', models.IntegerField()),
                ('popular_course_price3', models.IntegerField()),
                ('expert_img1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('expert_img2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('expert_img3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('expert_img4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('expert_name1', models.CharField(max_length=300)),
                ('expert_name2', models.CharField(max_length=300)),
                ('expert_name3', models.CharField(max_length=300)),
                ('expert_name4', models.CharField(max_length=300)),
            ],
        ),
    ]
