# Generated by Django 4.0.4 on 2022-05-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=1000)),
                ('lname', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=1000)),
                ('locality', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('state', models.CharField(max_length=1000)),
                ('zip', models.IntegerField()),
                ('country', models.CharField(max_length=1000)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=1000)),
                ('code', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('HQ', models.CharField(max_length=1000)),
                ('CA', models.CharField(max_length=1000)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
