# Generated by Django 4.0.4 on 2022-05-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eApp', '0003_alter_contact_locality'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contacting',
        ),
    ]
