# Generated by Django 4.0.4 on 2022-05-27 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eApp', '0004_rename_contact_contacting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacting',
            name='zip',
        ),
    ]
