# Generated by Django 4.0.4 on 2022-05-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eApp', '0005_remove_contacting_zip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacting',
            name='code',
        ),
    ]
