# Generated by Django 4.0.4 on 2022-06-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eApp', '0006_remove_contacting_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacting',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='filepath'),
        ),
    ]
